version: '3'
services:
  gton_extractor_withdraw_wusdn_bnb:
    image: badconfig/lp_withdraw_extractor
    container_name: gton_extractor_withdraw_wusdn_bnb
    tty: true
    environment:
      - CHAIN_URL=https://api.bscscan.com/
      - API_KEY=28N6H9NXCCT6F3VAH1SQAJJXKYPHSFYBBA
      - TOKEN_ADDRESS=0x069784dd0e8326c849075270c14903b77a416cc2
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000008e0d85c79e47498a6ee3c82c3c6f4105ab666737
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - METADATA=0000000000000000000000000000000000000000000000000000000000000002
      - POLLER_ID=20
      - TOKEN_DIGITS=0
    networks:
        - app-network
  gton_extractor_withdraw_wdpi_bnb:
    image: badconfig/lp_withdraw_extractor
    container_name: gton_extractor_withdraw_wdpi_bnb
    tty: true
    environment:
      - CHAIN_URL=https://api.bscscan.com/
      - API_KEY=74BI181QSASXCMIUN7UACFX33EU45F8NII
      - TOKEN_ADDRESS=0x57d2879fa09fbc93d0b21122819a408a52a2ddaa
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000008e0d85c79e47498a6ee3c82c3c6f4105ab666737
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - METADATA=0000000000000000000000000000000000000000000000000000000000000002
      - POLLER_ID=19
      - TOKEN_DIGITS=0
    networks:
        - app-network
  gton_extractor_deposit_wusdn_bnb:
    image: badconfig/gton_extractor
    container_name: gton_extractor_deposit_wusdn_bnb
    tty: true
    environment:
      - CHAIN_URL=https://api.bscscan.com/
      - API_KEY=EKJSR6MTUYHETQQ4NDK9D3YJZI3TWNRD39
      - TOKEN_ADDRESS=0x069784dd0e8326c849075270c14903b77a416cc2
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000008e0d85c79e47498a6ee3c82c3c6f4105ab666737
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - METADATA=0000000000000000000000000000000000000000000000000000000000000001
      - POLLER_ID=18
      - TOKEN_DIGITS=0
    networks:
        - app-network
  gton_extractor_deposit_wdpi_bnb:
    image: badconfig/gton_extractor
    container_name: gton_extractor_deposit_wdpi_bnb
    tty: true
    environment:
      - CHAIN_URL=https://api.bscscan.com/
      - API_KEY=B8UD9JWSTC8IFXIYSUYEWT6FZ3ZTYKAMG4
      - TOKEN_ADDRESS=0x57d2879fa09fbc93d0b21122819a408a52a2ddaa
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000008e0d85c79e47498a6ee3c82c3c6f4105ab666737
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - METADATA=0000000000000000000000000000000000000000000000000000000000000001
      - POLLER_ID=17
      - TOKEN_DIGITS=0
    networks:
        - app-network
  lp_wusdn_bnb_subs_extractor:
    image: badconfig/graviton_subs_extractor
    container_name: lp_wudn_bnb_subs_extractor
    tty: true
    environment:
      - CHAIN_URL=https://api.ftmscan.com/
      - API_KEY=Q5XTIQA5F8JBAPBUXPAUD7YC8U4XX3I6SC
      - TOKEN_ADDRESS=0xE9Abbd09172bf853EE297739e0DE7e9420991e5F
      - TRANSFER_EVENT_TOPIC=0xc817d75deaa278e988c41cf549ef38fe195ab65e0e64cd67ba47f0d185690d58
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=16
    networks:
        - app-network
  lp_wdpi_bnb_subs_extractor:
    image: badconfig/graviton_subs_extractor
    container_name: lp_wdpi_bnb_subs_extractor
    tty: true
    environment:
      - CHAIN_URL=https://api.ftmscan.com/
      - API_KEY=JU53HUTB11CQHYIY7KJ3KCWTUNRVDXG6X5
      - TOKEN_ADDRESS=0x7BE1b5de2887d99e17B1baBE07726b10af27c5Fb
      - TRANSFER_EVENT_TOPIC=0xc817d75deaa278e988c41cf549ef38fe195ab65e0e64cd67ba47f0d185690d58
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=15
    networks:
        - app-network
  graviton_subs_extractor:
    image: badconfig/graviton_subs_extractor
    container_name: graviton_subs_extractor
    tty: true
    environment:
      - CHAIN_URL=https://api.ftmscan.com/
      - API_KEY=584WA7RD7373A1SUHS1KTT8SYMIA9FIBW4
      - TOKEN_ADDRESS=0xD65Fc8A49715845c180CaE2C4c72aeF0158fe0cD
      - TRANSFER_EVENT_TOPIC=0xc817d75deaa278e988c41cf549ef38fe195ab65e0e64cd67ba47f0d185690d58
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=14
    networks:
        - app-network
  graviton_api_server:
    image: badconfig/graviton_api_server
    container_name: graviton_api_server
    tty: true
    environment:
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
    ports:
      - "8088:8088"
    networks:
        - app-network
  gton_extractor_dai:
    image: badconfig/gton_extractor
    container_name: gton_extractor_dai
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=IWEDC3PF1KICVVKWS8FUS95HKUK2J3MWRG
      - TOKEN_ADDRESS=0x6b175474e89094c44da98b954eedeac495271d0f
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=1
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_usdt:
    image: badconfig/gton_extractor
    container_name: gton_extractor_usdt
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=1IQ7UKV483632434FE3UI5H73RB1SDRJMK
      - TOKEN_ADDRESS=0xdac17f958d2ee523a2206206994597c13d831ec7
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=2
      - TOKEN_DIGITS=6
    networks:
        - app-network
  gton_extractor_usdc:
    image: badconfig/gton_extractor
    container_name: gton_extractor_usdc
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=A5AFB61BEM6AT61MB9133V2H549WBWCKFF
      - TOKEN_ADDRESS=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=3
      - TOKEN_DIGITS=6
    networks:
        - app-network
  gton_extractor_busd:
    image: badconfig/gton_extractor
    container_name: gton_extractor_busd
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=VHP2R9BVK3GDTXDXUDM39ZW3NE5HRD63M2
      - TOKEN_ADDRESS=0x4fabb145d64652a948d72533023f6e7a623c7c53
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=4
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_husd:
    image: badconfig/gton_extractor
    container_name: gton_extractor_husd
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=57PY5HEDMYEXXCVRU63II4YXVKE8W5Z2EM
      - TOKEN_ADDRESS=0xdf574c24545e5ffecb9a659c229253d4111d87e1
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=5
      - TOKEN_DIGITS=8
    networks:
        - app-network
  gton_extractor_tusd:
    image: badconfig/gton_extractor
    container_name: gton_extractor_tusd
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=K28X5I9UARSN9EJPQDA3CH6CJGEUNW45AY
      - TOKEN_ADDRESS=0x0000000000085d4780B73119b644AE5ecd22b376
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=6
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_ust:
    image: badconfig/gton_extractor
    container_name: gton_extractor_ust
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=Y7MBXIGDTETR4CQTXYEN3P9TQYCUSXXF8B
      - TOKEN_ADDRESS=0xa47c8bf37f92abed4a126bda807a7b7498661acd
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=7
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_susd:
    image: badconfig/gton_extractor
    container_name: gton_extractor_susd
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=AJJ6ZPSF84ZWY8B4S6UPHKBRG1BYPA7JMN
      - TOKEN_ADDRESS=0x57ab1ec28d129707052df4df418d58a2d46d5f51
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=8
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_usdk:
    image: badconfig/gton_extractor
    container_name: gton_extractor_usdk
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=Y3SYF47756AQYT1W8XKEA237Y6B9XVE483
      - TOKEN_ADDRESS=0x1c48f86ae57291f7686349f12601910bd8d470bb
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=9
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_usdp:
    image: badconfig/gton_extractor
    container_name: gton_extractor_usdp
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=URKEFIWTECZCJNSA83UPRGKW9HVBV5U9MV
      - TOKEN_ADDRESS=0x1456688345527bE1f37E9e627DA0837D6f08C925
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=10
      - TOKEN_DIGITS=18
    networks:
        - app-network
  gton_extractor_gusd:
    image: badconfig/gton_extractor
    container_name: gton_extractor_gusd
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=23NZPABYQ9V1QDHW26KRVK41E45I4CJXAE
      - TOKEN_ADDRESS=0x056fd409e1d7a124bd7017459dfea2f387b6d5cd
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=11
      - TOKEN_DIGITS=2
    networks:
        - app-network
  gton_extractor_usdn:
    image: badconfig/gton_extractor
    container_name: gton_extractor_usdn
    tty: true
    environment:
      - CHAIN_URL=https://api.etherscan.io/
      - API_KEY=XAYGCRGDREUH9YX91XGTFYB9Q2RX47I26D
      - TOKEN_ADDRESS=0x674C6Ad92Fd080e4004b2312b45f796a192D27a0
      - TRANSFER_EVENT_TOPIC=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
      - WALLET_ADDR=0x0000000000000000000000005b088d0fd3a57063baad9f82cd0c3c0110e57204
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres:5432/diesel_db
      - POLLER_ID=12
      - TOKEN_DIGITS=18
    networks:
        - app-network
  postgres:
    image: "postgres:13.2"
    container_name: postgres_db_transactions
    restart: unless-stopped
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: sdfjksfu2jkl45g343b
      POSTGRES_USER: docker
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pg_poll_data:/var/lib/postgresql/data
volumes:
  pg_poll_data:
networks:
  app-network:
    driver: bridge

