version: '3'
services:
  cola_extractor:
    image: badconfig/cola_extractor
    container_name: cola_extractor
    tty: true
    volumes:
      - ./extractor_v2_cola/cola.yaml:/cola_extractor/cola.yaml
    networks:
        - app-network
  postgres:
    image: "postgres:13.2"
    container_name: postgres_db_transactions
    restart: unless-stopped
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: sdfjksfu2jkl45g343b
      POSTGRES_USER: docker
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pg_poll_data:/var/lib/postgresql/data
volumes:
  pg_poll_data:
networks:
  app-network:
    driver: bridge

